# Generated by Django 4.2.27 on 2026-01-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation', models.CharField(max_length=300)),
                ('equation_html', models.CharField(max_length=500)),
                ('reaction_type', models.CharField(choices=[('synthesis', 'Síntesis'), ('decomposition', 'Descomposición'), ('single-replacement', 'Sustitución Simple'), ('double-replacement', 'Sustitución Doble'), ('combustion', 'Combustión'), ('acid-base', 'Ácido-Base'), ('redox', 'Oxidación-Reducción'), ('precipitation', 'Precipitación')], max_length=20)),
                ('difficulty_level', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='intermediate', max_length=15)),
                ('reactants', models.JSONField()),
                ('products', models.JSONField()),
                ('conditions', models.JSONField(default=dict)),
                ('enthalpy_change', models.FloatField(blank=True, null=True)),
                ('is_exothermic', models.BooleanField(default=True)),
                ('animation_data', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('real_world_applications', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reacción',
                'verbose_name_plural': 'Reacciones',
                'ordering': ['difficulty_level', 'reaction_type'],
            },
        ),
        migrations.CreateModel(
            name='ReactionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reactant', 'Reactivo'), ('product', 'Producto'), ('catalyst', 'Catalizador')], max_length=10)),
                ('coefficient', models.IntegerField(default=1)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.element')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
            options={
                'unique_together': {('reaction', 'element', 'role')},
            },
        ),
        migrations.AddField(
            model_name='reaction',
            name='elements',
            field=models.ManyToManyField(through='reactions.ReactionElement', to='elements.element'),
        ),
    ]
