# Generated by Django 4.2.27 on 2026-01-05 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_es', models.CharField(max_length=100, verbose_name='Nombre en español')),
                ('structure_3d', models.JSONField(default=dict, help_text='\n        {\n            "atoms": [\n                {"element": "H", "position": [0, 0, 0]},\n                {"element": "O", "position": [0.96, 0, 0]},\n                {"element": "H", "position": [1.5, 0.6, 0]}\n            ],\n            "bonds": [\n                {"from": 0, "to": 1, "type": "covalent", "order": 1},\n                {"from": 1, "to": 2, "type": "covalent", "order": 1}\n            ],\n            "geometry": "bent"\n        }\n        ')),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('is_polar', models.BooleanField(null=True)),
                ('state_at_room_temp', models.CharField(blank=True, choices=[('solid', 'Sólido'), ('liquid', 'Líquido'), ('gas', 'Gas')], max_length=20)),
            ],
            options={
                'verbose_name': 'Molécula',
                'verbose_name_plural': 'Moléculas',
                'ordering': ['formula'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la reacción')),
                ('equation', models.CharField(help_text='Ej: 2H2 + O2 → 2H2O', max_length=500, verbose_name='Ecuación química')),
                ('equation_balanced', models.BooleanField(default=True, help_text='Si la ecuación está balanceada')),
                ('reaction_type', models.CharField(choices=[('synthesis', 'Síntesis'), ('decomposition', 'Descomposición'), ('single_replacement', 'Sustitución Simple'), ('double_replacement', 'Sustitución Doble'), ('combustion', 'Combustión'), ('redox', 'Oxidación-Reducción'), ('acid_base', 'Ácido-Base'), ('precipitation', 'Precipitación'), ('complexation', 'Complejación'), ('organic', 'Reacción Orgánica')], db_index=True, max_length=20)),
                ('is_reversible', models.BooleanField(default=False, verbose_name='Es reversible')),
                ('energy_change', models.CharField(choices=[('exothermic', 'Exotérmica'), ('endothermic', 'Endotérmica'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('enthalpy_change', models.FloatField(blank=True, help_text='ΔH en kJ/mol', null=True)),
                ('activation_energy', models.FloatField(blank=True, help_text='Energía de activación en kJ/mol', null=True)),
                ('requires_catalyst', models.BooleanField(default=False)),
                ('catalyst', models.CharField(blank=True, max_length=100)),
                ('temperature_range', models.CharField(blank=True, help_text='Rango de temperatura en °C', max_length=50)),
                ('pressure_conditions', models.CharField(blank=True, max_length=50)),
                ('animation_data', models.JSONField(blank=True, default=dict, help_text='\n        Structure:\n        {\n            "reactants": [\n                {"molecule": "H2", "count": 2, "atoms": [{"element": "H", "position": [0,0,0]}]}\n            ],\n            "products": [\n                {"molecule": "H2O", "count": 2, "atoms": [...]}\n            ],\n            "bond_changes": [\n                {"type": "break", "from": [0,1], "step": 1},\n                {"type": "form", "atoms": [0,2], "step": 2}\n            ],\n            "animation_steps": [\n                {"step": 1, "duration_ms": 1000, "description": "Ruptura de enlaces H-H"}\n            ],\n            "total_duration_ms": 5000\n        }\n        ')),
                ('difficulty_level', models.PositiveIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Universitario'), (5, 'Profesional')], default=1)),
                ('educational_notes', models.TextField(blank=True, help_text='Explicación básica para mostrar antes de la IA', verbose_name='Notas educativas')),
                ('real_world_examples', models.TextField(blank=True, verbose_name='Ejemplos del mundo real')),
                ('safety_warnings', models.TextField(blank=True, verbose_name='Advertencias de seguridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verificado por un químico')),
            ],
            options={
                'verbose_name': 'Reacción',
                'verbose_name_plural': 'Reacciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReactionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reactant', 'Reactivo'), ('product', 'Producto'), ('catalyst', 'Catalizador')], max_length=20)),
                ('coefficient', models.PositiveIntegerField(default=1, help_text='Coeficiente estequiométrico')),
                ('oxidation_state', models.IntegerField(blank=True, help_text='Estado de oxidación en esta reacción', null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_reactions', to='elements.element')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_elements', to='reactions.reaction')),
            ],
            options={
                'verbose_name': 'Elemento en reacción',
                'verbose_name_plural': 'Elementos en reacciones',
            },
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['reaction_type'], name='reactions_r_reactio_e02c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['difficulty_level'], name='reactions_r_difficu_56ed45_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['is_verified'], name='reactions_r_is_veri_b067b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reactionelement',
            unique_together={('reaction', 'element', 'role')},
        ),
    ]
