# Generated by Django 4.2.27 on 2026-01-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('atomic_number', models.IntegerField(unique=True)),
                ('atomic_mass', models.FloatField()),
                ('category', models.CharField(choices=[('alkali-metal', 'Metal Alcalino'), ('alkaline-earth', 'Metal Alcalinotérreo'), ('transition-metal', 'Metal de Transición'), ('post-transition-metal', 'Metal Post-Transición'), ('metalloid', 'Metaloide'), ('nonmetal', 'No Metal'), ('halogen', 'Halógeno'), ('noble-gas', 'Gas Noble'), ('lanthanide', 'Lantánido'), ('actinide', 'Actínido')], max_length=25)),
                ('electron_config', models.CharField(max_length=100)),
                ('electrons_per_shell', models.JSONField(default=list)),
                ('valence_electrons', models.IntegerField(default=0)),
                ('electronegativity', models.FloatField(blank=True, null=True)),
                ('ionization_energy', models.FloatField(blank=True, null=True)),
                ('electron_affinity', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('melting_point', models.FloatField(blank=True, null=True)),
                ('boiling_point', models.FloatField(blank=True, null=True)),
                ('period', models.IntegerField()),
                ('group', models.IntegerField(blank=True, null=True)),
                ('color_hex', models.CharField(default='#CCCCCC', max_length=7)),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['atomic_number'],
            },
        ),
    ]
