# Generated by Django 4.2.27 on 2026-01-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('atomic_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('name_es', models.CharField(max_length=50, verbose_name='Nombre en español')),
                ('category', models.CharField(choices=[('alkali-metal', 'Metal alcalino'), ('alkaline-earth', 'Metal alcalinotérreo'), ('transition-metal', 'Metal de transición'), ('post-transition-metal', 'Metal post-transición'), ('metalloid', 'Metaloide'), ('nonmetal', 'No metal'), ('halogen', 'Halógeno'), ('noble-gas', 'Gas noble'), ('lanthanide', 'Lantánido'), ('actinide', 'Actínido'), ('unknown', 'Desconocido')], max_length=25)),
                ('atomic_mass', models.FloatField(help_text='Masa atómica en u')),
                ('density', models.FloatField(blank=True, help_text='Densidad en g/cm³', null=True)),
                ('melting_point', models.FloatField(blank=True, help_text='Punto de fusión en K', null=True)),
                ('boiling_point', models.FloatField(blank=True, help_text='Punto de ebullición en K', null=True)),
                ('electronegativity', models.FloatField(blank=True, help_text='Electronegatividad de Pauling', null=True)),
                ('electron_affinity', models.FloatField(blank=True, help_text='Afinidad electrónica en kJ/mol', null=True)),
                ('ionization_energy', models.FloatField(blank=True, help_text='Primera energía de ionización en kJ/mol', null=True)),
                ('electron_config', models.CharField(max_length=100, verbose_name='Configuración electrónica')),
                ('oxidation_states', models.CharField(blank=True, help_text='Estados de oxidación comunes separados por coma', max_length=100)),
                ('group', models.PositiveIntegerField(help_text='Grupo (1-18)')),
                ('period', models.PositiveIntegerField(help_text='Período (1-7)')),
                ('block', models.CharField(help_text='Bloque (s, p, d, f)', max_length=2)),
                ('color_hex', models.CharField(default='#CCCCCC', help_text='Color hexadecimal para visualización', max_length=7)),
                ('cpk_color', models.CharField(default='#CCCCCC', help_text='Color CPK estándar', max_length=7)),
                ('atomic_radius', models.FloatField(blank=True, help_text='Radio atómico en pm', null=True)),
                ('covalent_radius', models.FloatField(blank=True, help_text='Radio covalente en pm', null=True)),
                ('van_der_waals_radius', models.FloatField(blank=True, help_text='Radio de van der Waals en pm', null=True)),
                ('discovered_by', models.CharField(blank=True, max_length=200)),
                ('year_discovered', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Descripción educativa del elemento')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['atomic_number'],
            },
        ),
    ]
